/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _4 from "./ModBalances.types";
import * as _5 from "./ModBalances.client";
export namespace contracts {
  export const ModBalances = { ..._4,
    ..._5
  };
}