/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = string;
export type QueryMsg = {
  get_balance: {
    address: string;
    denom: string;
  };
} | {
  get_cw20_balance: {
    address: string;
    cw20_contract: string;
  };
} | {
  has_balance_comparator: HasBalanceComparator;
};
export type BalanceComparator = "eq" | "ne" | "gt" | "gte" | "lt" | "lte";
export type Balance = {
  native: NativeBalance;
} | {
  cw20: Cw20CoinVerified;
};
export type Uint128 = string;
export type NativeBalance = Coin[];
export type Addr = string;
export interface HasBalanceComparator {
  address: string;
  comparator: BalanceComparator;
  required_balance: Balance;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Cw20CoinVerified {
  address: Addr;
  amount: Uint128;
}
export type Binary = string;
export interface QueryResponseForBinary {
  data: Binary;
  result: boolean;
}