/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface CheckOwnerOfNftResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface CheckOwnerOfNft {
  address: string;
  nft_address: string;
  token_id: string;
  [k: string]: unknown;
}
export interface CheckProposalStatusResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export type Status = "execution_failed" | "open" | "rejected" | "passed" | "executed" | "closed";
export interface CheckProposalStatus {
  dao_address: string;
  proposal_id: number;
  status: Status;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  query_result: {
    [k: string]: unknown;
  };
};
export interface GenericQueryResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface GetBalanceResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface GetCw20BalanceResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface HasBalanceGteResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export type Balance = {
  native: NativeBalance;
} | {
  cw20: Cw20CoinVerified;
};
export type Uint128 = string;
export type NativeBalance = Coin[];
export type Addr = string;
export interface HasBalanceGte {
  address: string;
  required_balance: Balance;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Cw20CoinVerified {
  address: Addr;
  amount: Uint128;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  [k: string]: unknown;
}
export type Queries = {
  query: {
    contract_addr: string;
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  has_balance_gte: HasBalanceGte;
} | {
  check_owner_of_nft: CheckOwnerOfNft;
} | {
  check_proposal_status: CheckProposalStatus;
} | {
  generic_query: GenericQuery;
} | {
  smart_query: SmartQueryHead;
};
export type ValueOrdering = "unit_above" | "unit_above_equal" | "unit_below" | "unit_below_equal" | "equal" | "not_equal";
export type ValueIndex = {
  key: string;
} | {
  index: number;
};
export type PathToValue = ValueIndex[];
export type SmartQueries = SmartQuery[];
export interface GenericQuery {
  contract_addr: string;
  msg: Binary;
  ordering: ValueOrdering;
  path_to_value: PathToValue;
  value: Binary;
  [k: string]: unknown;
}
export interface SmartQueryHead {
  contract_addr: string;
  msg: Binary;
  ordering: ValueOrdering;
  path_to_query_value: PathToValue;
  queries: SmartQueries;
  value: Binary;
  [k: string]: unknown;
}
export interface SmartQuery {
  contract_addr: string;
  msg: Binary;
  path_to_msg_value: PathToValue;
  path_to_query_value: PathToValue;
  [k: string]: unknown;
}
export interface QueryConstructResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface QueryConstruct {
  rules: Queries[];
  [k: string]: unknown;
}
export type QueryMsg = {
  get_balance: {
    address: string;
    denom: string;
    [k: string]: unknown;
  };
} | {
  get_cw20_balance: {
    address: string;
    cw20_contract: string;
    [k: string]: unknown;
  };
} | {
  has_balance_gte: HasBalanceGte;
} | {
  check_owner_of_nft: CheckOwnerOfNft;
} | {
  check_proposal_status: CheckProposalStatus;
} | {
  generic_query: GenericQuery;
} | {
  query_construct: QueryConstruct;
} | {
  smart_query: SmartQueryHead;
};
export interface QueryMultiResponse {
  data: string[];
  [k: string]: unknown;
}
export interface RuleResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}
export interface SmartQueryResponse {
  data: Binary;
  result: boolean;
  [k: string]: unknown;
}