/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner_addr?: string | null;
}
export type ExecuteMsg = {
  update_config: {
    owner_addr: string;
  };
} | {
  deploy: {
    kind: VersionKind;
    module_instantiate_info: ModuleInstantiateInfo;
  };
} | {
  remove: {
    contract_name: string;
    version: [number, number];
  };
} | {
  update_metadata: {
    changelog_url?: string | null;
    contract_name: string;
    schema?: string | null;
    version: [number, number];
  };
} | {
  proxy: {
    msg: WasmMsg;
  };
};
export type VersionKind = "library" | "manager" | "tasks" | "agents";
export type Binary = string;
export type WasmMsg = {
  execute: {
    contract_addr: string;
    funds: Coin[];
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  instantiate: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  migrate: {
    contract_addr: string;
    msg: Binary;
    new_code_id: number;
    [k: string]: unknown;
  };
} | {
  update_admin: {
    admin: string;
    contract_addr: string;
    [k: string]: unknown;
  };
} | {
  clear_admin: {
    contract_addr: string;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export interface ModuleInstantiateInfo {
  changelog_url?: string | null;
  checksum: string;
  code_id: number;
  commit_id: string;
  contract_name: string;
  msg: Binary;
  schema?: string | null;
  version: [number, number];
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {};
} | {
  latest_contracts: {};
} | {
  latest_contract: {
    contract_name: string;
  };
} | {
  versions_by_contract_name: {
    contract_name: string;
    from_index?: number | null;
    limit?: number | null;
  };
} | {
  contract_names: {
    from_index?: number | null;
    limit?: number | null;
  };
} | {
  all_entries: {
    from_index?: number | null;
    limit?: number | null;
  };
};
export type Addr = string;
export type ArrayOfEntryResponse = EntryResponse[];
export interface EntryResponse {
  contract_name: string;
  metadata: ContractMetadataResponse;
}
export interface ContractMetadataResponse {
  changelog_url?: string | null;
  checksum: string;
  code_id: number;
  commit_id: string;
  contract_addr: Addr;
  kind: VersionKind;
  schema?: string | null;
  version: [number, number];
}
export interface Config {
  owner_addr: Addr;
}
export type ArrayOfString = string[];
export type Nullable_ContractMetadataResponse = ContractMetadataResponse | null;
export type ArrayOfContractMetadataResponse = ContractMetadataResponse[];