/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  agent_nomination_duration?: number | null;
  croncat_manager_key: [string, [number, number]];
  croncat_tasks_key: [string, [number, number]];
  max_slot_passover?: number | null;
  min_active_reserve?: number | null;
  min_coin_for_agent_registration?: number | null;
  min_tasks_per_agent?: number | null;
  owner_addr?: string | null;
  version?: string | null;
}
export type ExecuteMsg = {
  register_agent: {
    payable_account_id?: string | null;
  };
} | {
  update_agent: {
    payable_account_id: string;
  };
} | {
  check_in_agent: {};
} | {
  unregister_agent: {};
} | {
  task_created_hook: TaskCreatedHookMsg;
} | {
  task_completed_hook: TaskCompletedHookMsg;
} | {
  update_config: {
    config: UpdateConfig;
  };
} | {
  tick: {};
} | {
  add_hook: {
    addr: string;
    prefix: string;
  };
} | {
  remove_hook: {
    addr: string;
    prefix: string;
  };
};
export type Addr = string;
export interface TaskCreatedHookMsg {}
export interface TaskCompletedHookMsg {
  agent_id: Addr;
  is_block_slot_task: boolean;
}
export interface UpdateConfig {
  agent_nomination_duration?: number | null;
  croncat_factory_addr?: string | null;
  croncat_manager_key?: [string, [number, number]] | null;
  croncat_tasks_key?: [string, [number, number]] | null;
  max_slot_passover?: number | null;
  min_active_reserve?: number | null;
  min_coins_for_agent_registration?: number | null;
  min_tasks_per_agent?: number | null;
  owner_addr?: string | null;
  paused?: boolean | null;
}
export type QueryMsg = {
  get_agent: {
    account_id: string;
  };
} | {
  get_agent_ids: {
    from_index?: number | null;
    limit?: number | null;
  };
} | {
  get_agent_tasks: {
    account_id: string;
  };
} | {
  config: {};
} | {
  hooks: {
    prefix: string;
  };
};
export interface Config {
  agent_nomination_block_duration: number;
  croncat_factory_addr: Addr;
  croncat_manager_key: [string, [number, number]];
  croncat_tasks_key: [string, [number, number]];
  max_slot_passover: number;
  min_active_reserve: number;
  min_coins_for_agent_registration: number;
  min_tasks_per_agent: number;
  owner_addr: Addr;
  paused: boolean;
}
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type AgentStatus = "active" | "pending";
export interface AgentResponse {
  agent?: AgentInfo | null;
}
export interface AgentInfo {
  balance: Uint128;
  last_executed_slot: number;
  payable_account_id: Addr;
  register_start: Timestamp;
  status: AgentStatus;
}
export interface GetAgentIdsResponse {
  active: Addr[];
  pending: Addr[];
}
export interface AgentTasksResponse {
  total_block_tasks: Uint64;
  total_cron_tasks: Uint64;
}
export interface HooksResponse {
  hooks: string[];
}