/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = string;
export type QueryMsg = {
  generic_query: GenericQuery;
};
export type Binary = string;
export type ValueOrdering = "unit_above" | "unit_above_equal" | "unit_below" | "unit_below_equal" | "equal" | "not_equal";
export type ValueIndex = {
  key: string;
} | {
  index: number;
};
export type PathToValue = ValueIndex[];
export interface GenericQuery {
  contract_addr: string;
  msg: Binary;
  ordering: ValueOrdering;
  path_to_value: PathToValue;
  value: Binary;
}
export interface QueryResponseForBinary {
  data: Binary;
  result: boolean;
}