/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  version?: string | null;
}
export type ExecuteMsg = string;
export type QueryMsg = {
  generic_query: GenericQuery;
} | {
  batch_query: {
    queries: CosmosQueryForWasmQuery[];
  };
};
export type Binary = string;
export type ValueOrdering = "unit_above" | "unit_above_equal" | "unit_below" | "unit_below_equal" | "equal" | "not_equal";
export type ValueIndex = {
  key: string;
} | {
  index: number;
};
export type PathToValue = ValueIndex[];
export type CosmosQueryForWasmQuery = {
  croncat: CroncatQuery;
} | {
  wasm: WasmQuery;
};
export type WasmQuery = {
  smart: {
    contract_addr: string;
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  raw: {
    contract_addr: string;
    key: Binary;
    [k: string]: unknown;
  };
} | {
  contract_info: {
    contract_addr: string;
    [k: string]: unknown;
  };
};
export interface GenericQuery {
  contract_addr: string;
  msg: Binary;
  ordering: ValueOrdering;
  path_to_value: PathToValue;
  value: Binary;
}
export interface CroncatQuery {
  check_result: boolean;
  contract_addr: string;
  msg: Binary;
}
export interface QueryResponseForBinary {
  data: Binary;
  result: boolean;
}