/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.14.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwCroncat.types";
import * as _1 from "./CwCroncat.client";
import * as _2 from "./CwRules.types";
import * as _3 from "./CwRules.client";
export namespace contracts {
  export const CwCroncat = { ..._0,
    ..._1
  };
  export const CwRules = { ..._2,
    ..._3
  };
}