/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _2 from "./ModNft.types";
import * as _3 from "./ModNft.client";
export namespace contracts {
  export const ModNft = { ..._2,
    ..._3
  };
}