/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _12 from "./CroncatManager.types";
import * as _13 from "./CroncatManager.client";
export namespace contracts {
  export const CroncatManager = { ..._12,
    ..._13
  };
}